services:
  postgres:
    image: postgres:15-alpine
    container_name: visualizate-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: visualizate
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: visualizate-redis
    restart: always
    ports:
      - '6380:6379'

  minio:
    image: minio/minio:latest
    container_name: visualizate-minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - '9002:9000'
      - '9003:9001'
    volumes:
      - minio_data:/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: visualizate-mailpit
    restart: always
    ports:
      - '1025:1025' # Puerto SMTP
      - '8025:8025' # Puerto Web UI
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    volumes:
      - mailpit_data:/data

volumes:
  postgres_data:
  minio_data:
  mailpit_data:
